checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - src/*

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.